/**
 * Shared types for cf_ai_canvas
 */

// Canvas element types supported by tldraw
export type ElementType =
  | "rectangle"
  | "ellipse"
  | "diamond"
  | "triangle"
  | "text"
  | "arrow"
  | "line"
  | "note"
  | "frame"
  | "star"
  | "cloud"
  | "hexagon";

// tldraw color palette
export type ElementColor =
  | "black"
  | "grey"
  | "blue"
  | "light-blue"
  | "violet"
  | "light-violet"
  | "red"
  | "light-red"
  | "orange"
  | "yellow"
  | "green"
  | "light-green"
  | "white";

export type ElementFill = "none" | "semi" | "solid" | "pattern";
export type ElementDash = "draw" | "solid" | "dashed" | "dotted";
export type ElementSize = "s" | "m" | "l" | "xl";
export type ElementFont = "draw" | "sans" | "serif" | "mono";

export interface CanvasElement {
  id: string;
  type: ElementType;
  x: number;
  y: number;
  width?: number;
  height?: number;
  text?: string;
  color?: ElementColor;
  fill?: ElementFill;
  dash?: ElementDash;
  size?: ElementSize;
  font?: ElementFont;
  // Arrow-specific
  start?: { x: number; y: number; boundTo?: string };
  end?: { x: number; y: number; boundTo?: string };
  // Metadata
  createdAt: string;
  updatedAt: string;
}

export interface CanvasSnapshot {
  version: string;
  name: string;
  elements: CanvasElement[];
  createdAt: string;
}

export interface CanvasState {
  elements: Record<string, CanvasElement>;
  viewportZoom: number;
  viewportX: number;
  viewportY: number;
}

// Environment bindings are generated by Wrangler into env.d.ts
// Use the global `Env` interface directly (extends Cloudflare.Env)
